version: '2'
services:
  vlup:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - default
    external_links:
      - api:core
    volumes:
      - /static
    cpu_shares: 2048
    mem_limit: 4000m
    mem_reservation: 2000m
  reverseproxy:
    image: "nginx:1.11.9-alpine"
    networks:
     - default
    ports:
      - "80:80"
    links:
      - "vlup"
    volumes_from:
      - "vlup"
    volumes:
      - ./reverseproxy:/etc/nginx
    cpu_shares: 128
    mem_limit: 100m
    mem_reservation: 20m
networks:
  default:
    driver: bridge
