version: '2'
services:
  vlup:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
     - /static
  reverseproxy:
    image: "nginx:1.11.9-alpine"
    ports:
     - "80:80"
    links:
     - "vlup"
    volumes_from:
     - "vlup"
    volumes:
     - ./reverseproxy:/etc/nginx