version: '2'
services:
  vlup:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - default
    external_links:
      - api:core
    volumes:
      - /static
    mem_limit: 700m
    mem_reservation: 500m
  reverseproxy:
    image: "nginx:1.11.9-alpine"
    networks:
     - default
    ports:
      - "80:80"
    links:
      - "vlup"
    volumes_from:
      - "vlup"
    volumes:
      - ./reverseproxy:/etc/nginx
networks:
  default:
    driver: bridge
