version: '3'

services:
  scheduler:
    build: .
    image: "vlup-newscraper:latest"
    links:
      - broker
    volumes:
      - .:/app:ro
    command: celery -A common.celery beat --max-interval 30 --loglevel=info -s /home/celery/db --pidfile /home/celery/pid
  worker:
    build: .
    image: "vlup-newscraper:latest"
    links:
      - broker
    volumes:
      - .:/app:ro
      - ./data:/app/data
    command: celery -A common.celery worker --loglevel=info
  broker:
    image: "rabbitmq:management-alpine"
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
