version: '3'

services:
  api:
    build: .
    image: "vlup-newscraper:latest"
    networks:
      - appserver_default
    ports:
      - "8000:8000"
    volumes:
      - .:/app:ro
    command: gunicorn --bind=0.0.0.0:8000 --workers=4 api:app
  scheduler:
    build: .
    image: "vlup-newscraper:latest"
    networks:
      - internal
    links:
      - broker
    volumes:
      - .:/app:ro
    command: celery -A common.celery beat --max-interval 30 --loglevel=info -s /home/celery/db --pidfile /home/celery/pid
  worker:
    build: .
    image: "vlup-newscraper:latest"
    networks:
      - internal
    links:
      - broker
    volumes:
      - .:/app:ro
      - ./data:/app/data
    command: celery -A common.celery worker --loglevel=info
  broker:
    image: "rabbitmq:management-alpine"
    networks:
      - internal
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
networks:
  internal:
    driver: bridge
  appserver_default:
    external: true
